source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/general/functions.vim
source $HOME/.config/nvim/keys/mappings.vim
" Plugin Configuration
luafile $HOME/.config/nvim/lua/treesitter.lua
source $HOME/.config/nvim/plug-config/better-whitespace.vim
source $HOME/.config/nvim/plug-config/coc/coc.vim
source $HOME/.config/nvim/plug-config/coc/coc-extensions.vim
source $HOME/.config/nvim/plug-config/floaterm.vim
source $HOME/.config/nvim/plug-config/fzf.vim
source $HOME/.config/nvim/plug-config/identline.vim
source $HOME/.config/nvim/plug-config/largefile.vim
source $HOME/.config/nvim/plug-config/leetcode.vim
source $HOME/.config/nvim/plug-config/minimap.vim
source $HOME/.config/nvim/plug-config/neoterm.vim
source $HOME/.config/nvim/plug-config/NERDcommenter.vim
source $HOME/.config/nvim/plug-config/openbrowser.vim
source $HOME/.config/nvim/plug-config/polyglot.vim
source $HOME/.config/nvim/plug-config/ranger.vim
source $HOME/.config/nvim/plug-config/rnvimr.vim
source $HOME/.config/nvim/plug-config/startify.vim
source $HOME/.config/nvim/plug-config/suda.vim
source $HOME/.config/nvim/plug-config/ultisnips.vim
source $HOME/.config/nvim/plug-config/vimtex.vim
source $HOME/.config/nvim/plug-config/vista.vim
source $HOME/.config/nvim/plug-config/visualShlerp.vim
source $HOME/.config/nvim/plug-config/vimtest.vim
source $HOME/.config/nvim/plug-config/grammarous.vim
source $HOME/.config/nvim/plug-config/minimap.vim
source $HOME/.config/nvim/plug-config/hop.vim
source $HOME/.config/nvim/plug-config/markdown-preview.vim
